# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-30 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='alias',
        ),
    ]
