# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-30 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20230130_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
