# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-08 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20230208_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='subject',
        ),
    ]
