# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-08 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20230208_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='alias',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='subject',
            field=models.TextField(default=''),
        ),
    ]
